### ISSUE TITLE
Does not work on Windows 2008

### ISSUE THREAD

**Issue by vincent-aguillaume** [voxpupuli/puppet-windowsfeature#39]
Remove Windows 2008 support from the README / Limitations.

**Comment by petems** [comment]
@vincent-aguillaume I'm not super experienced but this works on my Vagrant 2008 box, what error are you seeing?

**Comment by vincent-aguillaume** [comment]
I believe Get-WindowsFeature only works on Windows Server 2008 R2 onwards.

**Comment by NetworkBytes** [comment]
I see the point, it says it supports Windows 2008 (non R2), 
Windows 2008 (non R2) doesn't have a PowerShell interface to install windows features

I whipped up support for Windows 2008 non R2  @ https://github.com/NetworkBytes/puppet-windowsfeature
hasn't been properly tested yet, will PR once Ive had the time to test it out

**Comment by maxgaulhofer** [comment]
I think this issue can be closed, as the new windowsfeature uses convert-to-xml, instead of json

**Comment by TraGicCode** [comment]
This is an old issue but going to verify this now.

**Comment by TraGicCode** [comment]
Yes this indeed doesn't work on Windows 2008 non-r2 currently.  As @vincent-aguillaume stated, get-windowsfeature doesn't even exist. 

@ghost Not sure if you're still alive since this is so old but your PR is way outdated and since then this module has been converted to using custom types and providers.  I will mark this as something that could be added in the future.  For now i'm going to update the metadata.json for this project.
