### ISSUE TITLE
Features which install/require .Net 3.5 on Windows 2012 R2 will fail (example Web-Webserver)

### ISSUE THREAD

**Issue by davidalexander83** [voxpupuli/puppet-windowsfeature#68]
Per https://p0w3rsh3ll.wordpress.com/2014/10/09/fix-the-infamous-0x800f0906-or-the-source-files-could-not-be-downloaded-error/

This can be reproduced on systems which have the 2966827/2966828 updates installed as per the article, by using windowsfeature to install Web-Webserver with installsubfeatures => true.

The workaround is to specify individual features for the role, however it's worth flagging to avoid unnecessary troubleshooting.

**Comment by TJM** [comment]
This was due to the source parameter not actually being passed properly. For Windows 2012 R2, you need to point `source => '\\someserver\os\2012R2\sxs'` for example, but the source parameter in 2.1.0 is not being passed. There are changes since that release which fix the issue. I am using #85 currently without issue.

**Comment by TraGicCode** [comment]
Closing this see i don't see how this is an with the module.
